### PR TITLE
Edge scenario test and fix

### PR DESCRIPTION
**Pull request by ggoranov**
TestEdgeCase failed without the fix.

### CODE REVIEW

**Comment by dim13** [comment]
Sadly, it fixes one issue, but introduces another. I'll probably have to do a major refactoring soon, to put things right.

**Comment by dim13** [comment]
@ggoranov please see #2 if it fixes you issue

**Comment by ggoranov** [comment]
@dim13 I appreciate much your quick response. The patch you've provided performs pretty much well - all cases pass and no new issues noticed. I'll keep you updated if any issue occurs.

Thanks for the help!

**Comment by dim13** [comment]
Fixed with #2

**Pull request closed without merging**
